/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + readiness (database reachability). Public; exposes no secrets. */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in; sets an HttpOnly session cookie
         * @description On success the JWT is delivered **only** as an `HttpOnly`, `SameSite=Lax` cookie (never in the body), so page scripts cannot read it. Failed attempts are rate limited per client IP + e-mail (5 per minute).
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the session cookie */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search and page customers
         * @description `search` matches case-insensitively anywhere in customer id, name, e-mail or city (trigram-indexed). Results include account count and current AUM.
         */
        get: operations["list_customers_api_v1_customers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customer profile with latest risk assessment */
        get: operations["get_customer_api_v1_customers__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portfolio valuation: totals, per-account totals, allocation and positions
         * @description Valued from the latest holdings snapshot at the latest synthetic prices. All aggregation runs in PostgreSQL (one GROUPING SETS query for account/asset-class/grand totals). Every account is listed, including those without positions. `freshness` tells the client which snapshot and price dates the numbers reflect. Each figure is computed exactly and rounded half-up to 2 dp independently, so a sum of rounded parts can differ from the rounded total by up to 0.01 per part.
         */
        get: operations["get_portfolio_api_v1_customers__customer_id__portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-side filtered, sorted and paginated transaction ledger
         * @description All filters combine with AND. `transaction_type` and `status` accept repeated values (`?transaction_type=BUY&transaction_type=SELL`). Ordering is deterministic (ties broken by transaction_id) so pages never shift between requests.
         */
        get: operations["list_transactions_api_v1_customers__customer_id__transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/transactions/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filter options (accounts, instruments, types, statuses, date range) with counts */
        get: operations["transaction_facets_api_v1_customers__customer_id__transactions_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Customer goals with funded % and consistency flags
         * @description `flags` highlights OVERDUE (date passed, not fully funded), OVERFUNDED, NAME_TYPE_MISMATCH (goal_name describes a different goal_type) and HIGH_PRIORITY_UNDERFUNDED (< 25 %).
         */
        get: operations["list_goals_api_v1_customers__customer_id__goals_get"];
        put?: never;
        /**
         * Create a validated goal
         * @description Rules: target_amount > 0; 0 <= current_funded_amount <= target_amount; target_date in the future. The goal id is assigned by the database.
         */
        post: operations["create_goal_api_v1_customers__customer_id__goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit selected goal fields
         * @description Partial update; only provided fields change. Cross-field rules are validated against the merged result. A changed target_date must be in the future; an overdue goal can still be edited without changing its date.
         */
        patch: operations["update_goal_api_v1_goals__goal_id__patch"];
        trace?: never;
    };
    "/api/v1/reports/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Firm-wide operational overview
         * @description Headline counts and AUM, top 10 customers by AUM, dataset-wide asset allocation, monthly settled BUY/SELL net flows for the last 12 months, top instruments by distinct holders, HIGH-priority goals under 25 % funded and data-quality exception counts. Every figure is an aggregate query; nothing is hard-coded.
         */
        get: operations["overview_api_v1_reports_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/imports/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate and import a transactions CSV (ADMIN)
         * @description Pipeline: structural checks (size, type, UTF-8, exact header) -> COPY into a staging table -> SQL rule validation -> merge valid rows, in one DB transaction.
         *
         *     * Rows with any rule violation are **rejected** with line number and reason; the rest are imported (partial acceptance).
         *     * Rows already present with identical values are counted as `duplicate_rows` and skipped, so re-uploading a file is idempotent.
         *     * A known `transaction_id` with *different* values is rejected (`CONFLICTS_WITH_EXISTING`), never overwritten.
         *     * A structurally invalid file is refused as a whole with 413/415/422.
         *
         *     The response returns up to 500 row errors; page through all of them with `GET /admin/imports/{id}/errors`.
         */
        post: operations["upload_transactions_api_v1_admin_imports_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Import history (seed and uploads), newest first (ADMIN) */
        get: operations["list_imports_api_v1_admin_imports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/imports/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One import batch (ADMIN) */
        get: operations["get_import_api_v1_admin_imports__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/imports/{batch_id}/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Row-level rejections of a batch, by line number (ADMIN) */
        get: operations["list_import_errors_api_v1_admin_imports__batch_id__errors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountStatus
         * @enum {string}
         */
        AccountStatus: "ACTIVE" | "DORMANT" | "CLOSED";
        /**
         * AccountType
         * @enum {string}
         */
        AccountType: "BROKERAGE" | "MUTUAL_FUND" | "RETIREMENT";
        /** AccountValuation */
        AccountValuation: {
            /** Market Value */
            market_value: number;
            /** Cost Basis */
            cost_basis: number;
            /** Unrealized Pnl */
            unrealized_pnl: number;
            /**
             * Unrealized Pnl Pct
             * @description unrealized_pnl / cost_basis x 100; null when cost basis is zero
             */
            unrealized_pnl_pct: number | null;
            /** Positions */
            positions: number;
            /** Account Id */
            account_id: string;
            account_type: components["schemas"]["AccountType"];
            /** Provider */
            provider: string;
            status: components["schemas"]["AccountStatus"];
            /**
             * Opened At
             * Format: date
             */
            opened_at: string;
        };
        /** AllocationRow */
        AllocationRow: {
            asset_class: components["schemas"]["AssetClass"];
            /** Market Value */
            market_value: number;
            /** Weight Pct */
            weight_pct: number;
        };
        /** AllocationSlice */
        AllocationSlice: {
            asset_class: components["schemas"]["AssetClass"];
            /** Market Value */
            market_value: number;
            /** Weight Pct */
            weight_pct: number;
            /** Positions */
            positions: number;
        };
        /**
         * AssetClass
         * @enum {string}
         */
        AssetClass: "EQUITY" | "ETF" | "MUTUAL_FUND" | "BOND" | "REIT" | "GSEC";
        /**
         * Band
         * @description Shared LOW/MEDIUM/HIGH scale (instrument risk band, goal priority, liquidity need).
         * @enum {string}
         */
        Band: "LOW" | "MEDIUM" | "HIGH";
        /** Body_upload_transactions_api_v1_admin_imports_transactions_post */
        Body_upload_transactions_api_v1_admin_imports_transactions_post: {
            /**
             * File
             * @description transactions CSV, UTF-8, max 25 MB
             */
            file: string;
        };
        /** CustomerListItem */
        CustomerListItem: {
            /** Customer Id */
            customer_id: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** City */
            city: string;
            /** State */
            state: string;
            kyc_status: components["schemas"]["KycStatus"];
            segment: components["schemas"]["Segment"];
            /** Accounts */
            accounts: number;
            /** Aum */
            aum: number;
        };
        /** CustomerPage */
        CustomerPage: {
            /** Items */
            items: components["schemas"]["CustomerListItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** CustomerProfile */
        CustomerProfile: {
            /** Customer Id */
            customer_id: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Phone */
            phone: string;
            /** City */
            city: string;
            /** State */
            state: string;
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /**
             * Onboarded At
             * Format: date
             */
            onboarded_at: string;
            kyc_status: components["schemas"]["KycStatus"];
            segment: components["schemas"]["Segment"];
            risk_profile: components["schemas"]["RiskProfileOut"] | null;
            /** Accounts */
            accounts: number;
            /** Goals */
            goals: number;
        };
        /** DataFreshness */
        DataFreshness: {
            /**
             * Snapshot Date
             * @description Holdings snapshot used for valuation
             */
            snapshot_date: string | null;
            /**
             * Price As Of
             * @description Latest price date among held instruments
             */
            price_as_of: string | null;
            /** Oldest Price As Of */
            oldest_price_as_of: string | null;
            /**
             * Stale Prices
             * @description True if any price predates the snapshot date
             */
            stale_prices: boolean;
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @example CUSTOMER_NOT_FOUND
             */
            code: string;
            /**
             * Message
             * @example Customer C9999 was not found
             */
            message: string;
            /**
             * Request Id
             * @example req_3f2a9c1b7d4e5f60
             */
            request_id: string | null;
            /** Details */
            details?: components["schemas"]["ErrorDetail"][] | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Field */
            field?: string | null;
            /** Location */
            location?: string | null;
            /** Message */
            message: string;
            /** Type */
            type?: string | null;
        };
        /**
         * ErrorResponse
         * @description Envelope for every non-2xx response.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** ExceptionCount */
        ExceptionCount: {
            /** Exception Type */
            exception_type: string;
            /** Rule */
            rule: string;
            /** Entity */
            entity: string;
            /** Count */
            count: number;
        };
        /** FacetOption */
        FacetOption: {
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /** GoalCreate */
        GoalCreate: {
            goal_type: components["schemas"]["GoalType"];
            /** Goal Name */
            goal_name: string;
            /**
             * Target Amount
             * @example 5000000
             */
            target_amount: number | string;
            /**
             * Current Funded Amount
             * @default 0
             * @example 5000000
             */
            current_funded_amount: number | string;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** @default MEDIUM */
            priority: components["schemas"]["Band"];
        };
        /**
         * GoalFlag
         * @enum {string}
         */
        GoalFlag: "OVERDUE" | "OVERFUNDED" | "NAME_TYPE_MISMATCH" | "HIGH_PRIORITY_UNDERFUNDED";
        /** GoalList */
        GoalList: {
            /** Items */
            items: components["schemas"]["GoalOut"][];
            summary: components["schemas"]["GoalSummary"];
        };
        /** GoalOut */
        GoalOut: {
            /** Goal Id */
            goal_id: string;
            /** Customer Id */
            customer_id: string;
            goal_type: components["schemas"]["GoalType"];
            /** Goal Name */
            goal_name: string;
            /** Target Amount */
            target_amount: number;
            /** Current Funded Amount */
            current_funded_amount: number;
            /** Remaining Amount */
            remaining_amount: number;
            /**
             * Funded Pct
             * @description current_funded_amount / target_amount x 100
             */
            funded_pct: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            priority: components["schemas"]["Band"];
            /** Flags */
            flags: components["schemas"]["GoalFlag"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** GoalSummary */
        GoalSummary: {
            /** Goals */
            goals: number;
            /** Total Target */
            total_target: number;
            /** Total Funded */
            total_funded: number;
            /** Funded Pct */
            funded_pct: number | null;
            /** Flagged */
            flagged: number;
        };
        /**
         * GoalType
         * @enum {string}
         */
        GoalType: "RETIREMENT" | "EDUCATION" | "HOME_PURCHASE" | "EMERGENCY_FUND" | "WEALTH_CREATION" | "TRAVEL";
        /**
         * GoalUpdate
         * @description Partial update. Cross-field rules are checked against the merged result.
         */
        GoalUpdate: {
            goal_type?: components["schemas"]["GoalType"] | null;
            /** Goal Name */
            goal_name?: string | null;
            /** Target Amount */
            target_amount?: (number | string) | null;
            /** Current Funded Amount */
            current_funded_amount?: (number | string) | null;
            /** Target Date */
            target_date?: string | null;
            priority?: components["schemas"]["Band"] | null;
        };
        /** Headline */
        Headline: {
            /** Customers */
            customers: number;
            /** Accounts */
            accounts: number;
            /** Active Accounts */
            active_accounts: number;
            /** Customers With Holdings */
            customers_with_holdings: number;
            /** Aum */
            aum: number;
            /** Transactions */
            transactions: number;
            /** Goals */
            goals: number;
            /** Snapshot Date */
            snapshot_date: string | null;
            /** Price As Of */
            price_as_of: string | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "unhealthy";
            /**
             * Database
             * @enum {string}
             */
            database: "healthy" | "unavailable";
            /** Environment */
            environment: string;
            /** Version */
            version: string;
        };
        /** ImportBatchOut */
        ImportBatchOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["ImportKind"];
            /** Source */
            source: string;
            status: components["schemas"]["ImportStatus"];
            /** Filename */
            filename: string;
            /** File Sha256 */
            file_sha256: string;
            /** File Bytes */
            file_bytes: number;
            /**
             * Uploaded By
             * @description E-mail of the uploading user; null for seed
             */
            uploaded_by: string | null;
            /** Total Rows */
            total_rows: number;
            /** Inserted Rows */
            inserted_rows: number;
            /**
             * Duplicate Rows
             * @description Already present with identical values (skipped)
             */
            duplicate_rows: number;
            /** Rejected Rows */
            rejected_rows: number;
            /** Error Message */
            error_message: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /** ImportBatchPage */
        ImportBatchPage: {
            /** Items */
            items: components["schemas"]["ImportBatchOut"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** ImportErrorPage */
        ImportErrorPage: {
            /** Items */
            items: components["schemas"]["ImportRowErrorOut"][];
            pagination: components["schemas"]["Pagination"];
        };
        /**
         * ImportKind
         * @enum {string}
         */
        ImportKind: "CUSTOMERS" | "ACCOUNTS" | "INSTRUMENTS" | "RISK_PROFILES" | "GOALS" | "HOLDINGS" | "TRANSACTIONS";
        /**
         * ImportReport
         * @description Upload response: the batch plus the first page of row-level rejections.
         */
        ImportReport: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["ImportKind"];
            /** Source */
            source: string;
            status: components["schemas"]["ImportStatus"];
            /** Filename */
            filename: string;
            /** File Sha256 */
            file_sha256: string;
            /** File Bytes */
            file_bytes: number;
            /**
             * Uploaded By
             * @description E-mail of the uploading user; null for seed
             */
            uploaded_by: string | null;
            /** Total Rows */
            total_rows: number;
            /** Inserted Rows */
            inserted_rows: number;
            /**
             * Duplicate Rows
             * @description Already present with identical values (skipped)
             */
            duplicate_rows: number;
            /** Rejected Rows */
            rejected_rows: number;
            /** Error Message */
            error_message: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Errors */
            errors: components["schemas"]["ImportRowErrorOut"][];
            /** Errors Total */
            errors_total: number;
            /** Errors Truncated */
            errors_truncated: boolean;
        };
        /** ImportRowErrorOut */
        ImportRowErrorOut: {
            /**
             * Line Number
             * @description Physical line in the uploaded file; header = 1
             */
            line_number: number;
            /** Severity */
            severity: string;
            /** Error Code */
            error_code: string;
            /** Field */
            field: string | null;
            /** Message */
            message: string;
            /** Raw Data */
            raw_data: {
                [key: string]: unknown;
            };
        };
        /**
         * ImportStatus
         * @enum {string}
         */
        ImportStatus: "PROCESSING" | "COMPLETED" | "FAILED";
        /** InstrumentHolders */
        InstrumentHolders: {
            /** Instrument Id */
            instrument_id: string;
            /** Symbol */
            symbol: string;
            /** Instrument Name */
            instrument_name: string;
            asset_class: components["schemas"]["AssetClass"];
            /** Holders */
            holders: number;
        };
        /**
         * KycStatus
         * @enum {string}
         */
        KycStatus: "VERIFIED" | "PENDING" | "REVIEW";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * @example viewer@finpilot.local
             */
            email: string;
            /**
             * Password
             * Format: password
             * @example Viewer@12345
             */
            password: string;
        };
        /** MonthlyFlow */
        MonthlyFlow: {
            /**
             * Month
             * Format: date
             */
            month: string;
            /** Buy Amount */
            buy_amount: number;
            /** Sell Amount */
            sell_amount: number;
            /** Net Invested */
            net_invested: number;
            /** Trades */
            trades: number;
        };
        /** Overview */
        Overview: {
            headline: components["schemas"]["Headline"];
            /** Top Customers */
            top_customers: components["schemas"]["TopCustomer"][];
            /** Allocation */
            allocation: components["schemas"]["AllocationRow"][];
            /** Monthly Net Flows */
            monthly_net_flows: components["schemas"]["MonthlyFlow"][];
            /** Top Instruments By Holders */
            top_instruments_by_holders: components["schemas"]["InstrumentHolders"][];
            /** High Priority Underfunded Goals */
            high_priority_underfunded_goals: components["schemas"]["UnderfundedGoal"][];
            /** Data Quality */
            data_quality: components["schemas"]["ExceptionCount"][];
        };
        /** Pagination */
        Pagination: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Pages */
            pages: number;
        };
        /** Portfolio */
        Portfolio: {
            /** Customer Id */
            customer_id: string;
            /**
             * Currency
             * @default INR
             */
            currency: string;
            freshness: components["schemas"]["DataFreshness"];
            totals: components["schemas"]["Valuation"];
            /** Accounts */
            accounts: components["schemas"]["AccountValuation"][];
            /** Allocation */
            allocation: components["schemas"]["AllocationSlice"][];
            /** Positions */
            positions: components["schemas"]["Position"][];
        };
        /** Position */
        Position: {
            /** Account Id */
            account_id: string;
            /** Instrument Id */
            instrument_id: string;
            /** Symbol */
            symbol: string;
            /** Instrument Name */
            instrument_name: string;
            asset_class: components["schemas"]["AssetClass"];
            /** Sector */
            sector: string | null;
            /** Risk Band */
            risk_band: string;
            /** Quantity */
            quantity: number;
            /** Avg Cost */
            avg_cost: number;
            /** Last Price */
            last_price: number;
            /**
             * Price As Of
             * Format: date
             */
            price_as_of: string;
            /** Market Value */
            market_value: number;
            /** Cost Basis */
            cost_basis: number;
            /** Unrealized Pnl */
            unrealized_pnl: number;
            /** Unrealized Pnl Pct */
            unrealized_pnl_pct: number | null;
            /** Weight Pct */
            weight_pct: number;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "Conservative" | "Moderate" | "Growth" | "Aggressive";
        /** RiskProfileOut */
        RiskProfileOut: {
            /** Risk Score */
            risk_score: number;
            risk_level: components["schemas"]["RiskLevel"];
            /**
             * Assessed At
             * Format: date
             */
            assessed_at: string;
            /** Horizon Years */
            horizon_years: number;
            /** Liquidity Need */
            liquidity_need: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "VIEWER" | "ADMIN";
        /**
         * Segment
         * @enum {string}
         */
        Segment: "Mass" | "Affluent" | "HNI";
        /** SessionOut */
        SessionOut: {
            user: components["schemas"]["UserOut"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** TopCustomer */
        TopCustomer: {
            /** Customer Id */
            customer_id: string;
            /** Full Name */
            full_name: string;
            /** Segment */
            segment: string;
            /** Aum */
            aum: number;
        };
        /**
         * TransactionFacets
         * @description Filter options limited to values that actually occur for this customer.
         */
        TransactionFacets: {
            /** Accounts */
            accounts: components["schemas"]["FacetOption"][];
            /** Instruments */
            instruments: components["schemas"]["FacetOption"][];
            /** Transaction Types */
            transaction_types: components["schemas"]["FacetOption"][];
            /** Statuses */
            statuses: components["schemas"]["FacetOption"][];
            /** Min Trade Date */
            min_trade_date: string | null;
            /** Max Trade Date */
            max_trade_date: string | null;
        };
        /** TransactionOut */
        TransactionOut: {
            /** Transaction Id */
            transaction_id: string;
            /** Account Id */
            account_id: string;
            /** Instrument Id */
            instrument_id: string;
            /** Symbol */
            symbol: string;
            /** Instrument Name */
            instrument_name: string;
            asset_class: components["schemas"]["AssetClass"];
            transaction_type: components["schemas"]["TransactionType"];
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Quantity */
            quantity: number;
            /** Price */
            price: number;
            /** Amount */
            amount: number;
            status: components["schemas"]["TransactionStatus"];
        };
        /** TransactionPage */
        TransactionPage: {
            /** Items */
            items: components["schemas"]["TransactionOut"][];
            pagination: components["schemas"]["Pagination"];
        };
        /**
         * TransactionStatus
         * @enum {string}
         */
        TransactionStatus: "SETTLED" | "PENDING" | "REVERSED";
        /**
         * TransactionType
         * @enum {string}
         */
        TransactionType: "BUY" | "SELL" | "DIVIDEND" | "FEE";
        /** UnderfundedGoal */
        UnderfundedGoal: {
            /** Goal Id */
            goal_id: string;
            /** Customer Id */
            customer_id: string;
            /** Full Name */
            full_name: string;
            /** Goal Type */
            goal_type: string;
            /** Target Amount */
            target_amount: number;
            /** Current Funded Amount */
            current_funded_amount: number;
            /** Funded Pct */
            funded_pct: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["Role"];
        };
        /** Valuation */
        Valuation: {
            /** Market Value */
            market_value: number;
            /** Cost Basis */
            cost_basis: number;
            /** Unrealized Pnl */
            unrealized_pnl: number;
            /**
             * Unrealized Pnl Pct
             * @description unrealized_pnl / cost_basis x 100; null when cost basis is zero
             */
            unrealized_pnl_pct: number | null;
            /** Positions */
            positions: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_customers_api_v1_customers_get: {
        parameters: {
            query?: {
                search?: string | null;
                kyc_status?: components["schemas"]["KycStatus"] | null;
                segment?: components["schemas"]["Segment"] | null;
                sort?: "customer_id" | "full_name" | "city" | "-aum" | "aum" | "-onboarded_at";
                /** @description 1-based page number */
                page?: number;
                /** @description Items per page (max 100) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_customer_api_v1_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer id, e.g. C0026 */
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_portfolio_api_v1_customers__customer_id__portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer id, e.g. C0026 */
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "customer_id": "C0026",
                     *       "currency": "INR",
                     *       "freshness": {
                     *         "snapshot_date": "2026-09-18",
                     *         "price_as_of": "2026-09-18",
                     *         "oldest_price_as_of": "2026-09-18",
                     *         "stale_prices": false
                     *       },
                     *       "totals": {
                     *         "market_value": 1953574.59,
                     *         "cost_basis": 1964360.97,
                     *         "unrealized_pnl": -10786.37,
                     *         "unrealized_pnl_pct": -0.55,
                     *         "positions": 19
                     *       },
                     *       "accounts": [
                     *         {
                     *           "account_id": "A00034",
                     *           "account_type": "RETIREMENT",
                     *           "provider": "Zenith Broking",
                     *           "status": "ACTIVE",
                     *           "opened_at": "2026-01-27",
                     *           "market_value": 1245566.63,
                     *           "cost_basis": 1218651.57,
                     *           "unrealized_pnl": 26915.06,
                     *           "unrealized_pnl_pct": 2.21,
                     *           "positions": 10
                     *         }
                     *       ],
                     *       "allocation": [
                     *         {
                     *           "asset_class": "EQUITY",
                     *           "market_value": 1804340.02,
                     *           "weight_pct": 92.36,
                     *           "positions": 12
                     *         }
                     *       ],
                     *       "positions": [
                     *         {
                     *           "account_id": "A00035",
                     *           "instrument_id": "I0019",
                     *           "symbol": "EQ019",
                     *           "instrument_name": "FinPilot Equity 19",
                     *           "asset_class": "EQUITY",
                     *           "sector": "Healthcare",
                     *           "risk_band": "MEDIUM",
                     *           "quantity": 166.282,
                     *           "avg_cost": 2551.4,
                     *           "last_price": 2215.39,
                     *           "price_as_of": "2026-09-18",
                     *           "market_value": 368379.48,
                     *           "cost_basis": 424251.89,
                     *           "unrealized_pnl": -55872.41,
                     *           "unrealized_pnl_pct": -13.17,
                     *           "weight_pct": 18.86
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_transactions_api_v1_customers__customer_id__transactions_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                account_id?: string | null;
                instrument_id?: string | null;
                transaction_type?: components["schemas"]["TransactionType"][] | null;
                status?: components["schemas"]["TransactionStatus"][] | null;
                sort?: "-trade_date" | "trade_date" | "-amount" | "amount";
                /** @description 1-based page number */
                page?: number;
                /** @description Items per page (max 100) */
                page_size?: number;
            };
            header?: never;
            path: {
                /** @description Customer id, e.g. C0026 */
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    transaction_facets_api_v1_customers__customer_id__transactions_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer id, e.g. C0026 */
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionFacets"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_goals_api_v1_customers__customer_id__goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer id, e.g. C0026 */
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalList"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_goal_api_v1_customers__customer_id__goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer id, e.g. C0026 */
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_goal_api_v1_goals__goal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    overview_api_v1_reports_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_transactions_api_v1_admin_imports_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_transactions_api_v1_admin_imports_transactions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "e1b20da2-5727-4c3d-94c3-01aed1d1d4e7",
                     *       "kind": "TRANSACTIONS",
                     *       "source": "UPLOAD",
                     *       "status": "COMPLETED",
                     *       "filename": "transactions.csv",
                     *       "file_sha256": "0096865ae283c06b14ebef5f74aed8ebc7692af5722aba664c26d16a641499b6",
                     *       "file_bytes": 304663,
                     *       "uploaded_by": "admin@finpilot.local",
                     *       "total_rows": 4554,
                     *       "inserted_rows": 0,
                     *       "duplicate_rows": 4550,
                     *       "rejected_rows": 4,
                     *       "started_at": "2026-10-06T12:39:48.424036Z",
                     *       "completed_at": "2026-10-06T12:39:48.433073Z",
                     *       "errors_total": 4,
                     *       "errors_truncated": false,
                     *       "errors": [
                     *         {
                     *           "line_number": 4552,
                     *           "severity": "REJECTED",
                     *           "error_code": "DUPLICATE_IN_FILE",
                     *           "field": "transaction_id",
                     *           "message": "transaction_id T0000026 already appears on line 27",
                     *           "raw_data": {
                     *             "transaction_id": "T0000026",
                     *             "amount": "16686.83",
                     *             "status": "SETTLED"
                     *           }
                     *         },
                     *         {
                     *           "line_number": 4553,
                     *           "severity": "REJECTED",
                     *           "error_code": "UNKNOWN_INSTRUMENT",
                     *           "field": "instrument_id",
                     *           "message": "instrument_id I9999 does not exist",
                     *           "raw_data": {
                     *             "transaction_id": "T0004551",
                     *             "instrument_id": "I9999",
                     *             "amount": "1000"
                     *           }
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ImportReport"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_imports_api_v1_admin_imports_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["ImportKind"] | null;
                /** @description 1-based page number */
                page?: number;
                /** @description Items per page (max 100) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchPage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_import_api_v1_admin_imports__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_import_errors_api_v1_admin_imports__batch_id__errors_get: {
        parameters: {
            query?: {
                /** @description 1-based page number */
                page?: number;
                /** @description Items per page (max 100) */
                page_size?: number;
            };
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportErrorPage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
