"""initial schema: core domain tables, import audit tables and staging table

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 17:33:41.512222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Sequences are not autogenerated; goals.goal_id defaults to G + zero-padded nextval.
    op.execute(sa.schema.CreateSequence(sa.Sequence("goal_id_seq", start=1)))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=3), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('onboarded_at', sa.Date(), nullable=False),
    sa.Column('kyc_status', sa.String(length=10), nullable=False),
    sa.Column('segment', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("customer_id ~ '^C[0-9]{4,}$'", name=op.f('ck_customers_id_format')),
    sa.CheckConstraint("kyc_status IN ('VERIFIED', 'PENDING', 'REVIEW')", name=op.f('ck_customers_kyc_status_valid')),
    sa.CheckConstraint("segment IN ('Mass', 'Affluent', 'HNI')", name=op.f('ck_customers_segment_valid')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_customers_email_lowercase')),
    sa.CheckConstraint('onboarded_at > date_of_birth', name=op.f('ck_customers_onboarded_after_birth')),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customers')),
    sa.UniqueConstraint('email', name=op.f('uq_customers_email'))
    )
    op.create_table('instruments',
    sa.Column('instrument_id', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('instrument_name', sa.String(length=120), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=40), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price_as_of', sa.Date(), nullable=False),
    sa.Column('risk_band', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(asset_class = 'EQUITY') = (sector IS NOT NULL)", name=op.f('ck_instruments_sector_only_for_equity')),
    sa.CheckConstraint("asset_class IN ('EQUITY', 'ETF', 'MUTUAL_FUND', 'BOND', 'REIT', 'GSEC')", name=op.f('ck_instruments_asset_class_valid')),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_instruments_currency_iso')),
    sa.CheckConstraint("exchange IN ('NSE', 'BSE', 'OTC')", name=op.f('ck_instruments_exchange_valid')),
    sa.CheckConstraint("instrument_id ~ '^I[0-9]{4,}$'", name=op.f('ck_instruments_id_format')),
    sa.CheckConstraint("risk_band IN ('LOW', 'MEDIUM', 'HIGH')", name=op.f('ck_instruments_risk_band_valid')),
    sa.CheckConstraint('last_price > 0', name=op.f('ck_instruments_price_positive')),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instruments')),
    sa.UniqueConstraint('symbol', name=op.f('uq_instruments_symbol'))
    )
    op.create_table('staging_transactions',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Text(), nullable=True),
    sa.Column('account_id', sa.Text(), nullable=True),
    sa.Column('instrument_id', sa.Text(), nullable=True),
    sa.Column('transaction_type', sa.Text(), nullable=True),
    sa.Column('trade_date', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Text(), nullable=True),
    sa.Column('price', sa.Text(), nullable=True),
    sa.Column('amount', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('batch_id', 'line_number', name=op.f('pk_staging_transactions')),
    prefixes=['UNLOGGED']
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('VIEWER', 'ADMIN')", name=op.f('ck_users_role_valid')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('accounts',
    sa.Column('account_id', sa.String(length=10), nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_id ~ '^A[0-9]{5,}$'", name=op.f('ck_accounts_id_format')),
    sa.CheckConstraint("account_type IN ('BROKERAGE', 'MUTUAL_FUND', 'RETIREMENT')", name=op.f('ck_accounts_type_valid')),
    sa.CheckConstraint("base_currency ~ '^[A-Z]{3}$'", name=op.f('ck_accounts_currency_iso')),
    sa.CheckConstraint("status IN ('ACTIVE', 'DORMANT', 'CLOSED')", name=op.f('ck_accounts_status_valid')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_accounts_customer_id_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('account_id', name=op.f('pk_accounts'))
    )
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_table('goals',
    sa.Column('goal_id', sa.String(length=12), server_default=sa.text("'G' || lpad(nextval('goal_id_seq')::text, 5, '0')"), nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('goal_type', sa.String(length=20), nullable=False),
    sa.Column('goal_name', sa.String(length=120), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_funded_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("goal_id ~ '^G[0-9]{5,}$'", name=op.f('ck_goals_id_format')),
    sa.CheckConstraint("goal_type IN ('RETIREMENT', 'EDUCATION', 'HOME_PURCHASE', 'EMERGENCY_FUND', 'WEALTH_CREATION', 'TRAVEL')", name=op.f('ck_goals_type_valid')),
    sa.CheckConstraint("priority IN ('LOW', 'MEDIUM', 'HIGH')", name=op.f('ck_goals_priority_valid')),
    sa.CheckConstraint('current_funded_amount >= 0', name=op.f('ck_goals_funded_non_negative')),
    sa.CheckConstraint('target_amount > 0', name=op.f('ck_goals_target_positive')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_goals_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal_id', name=op.f('pk_goals'))
    )
    op.create_index(op.f('ix_goals_customer_id'), 'goals', ['customer_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('total_rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('inserted_rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rejected_rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('CUSTOMERS', 'ACCOUNTS', 'INSTRUMENTS', 'RISK_PROFILES', 'GOALS', 'HOLDINGS', 'TRANSACTIONS')", name=op.f('ck_import_batches_kind_valid')),
    sa.CheckConstraint("source IN ('SEED', 'UPLOAD')", name=op.f('ck_import_batches_source_valid')),
    sa.CheckConstraint("status IN ('PROCESSING', 'COMPLETED', 'FAILED')", name=op.f('ck_import_batches_status_valid')),
    sa.CheckConstraint("total_rows = inserted_rows + duplicate_rows + rejected_rows OR status <> 'COMPLETED'", name=op.f('ck_import_batches_counts_reconcile')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_import_batches_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    op.create_index(op.f('ix_import_batches_kind'), 'import_batches', ['kind', sa.literal_column('started_at DESC')], unique=False)
    op.create_table('risk_profiles',
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('assessed_at', sa.Date(), nullable=False),
    sa.Column('risk_score', sa.SmallInteger(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('horizon_years', sa.SmallInteger(), nullable=False),
    sa.Column('liquidity_need', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("liquidity_need IN ('LOW', 'MEDIUM', 'HIGH')", name=op.f('ck_risk_profiles_liquidity_valid')),
    sa.CheckConstraint("risk_level IN ('Conservative', 'Moderate', 'Growth', 'Aggressive')", name=op.f('ck_risk_profiles_level_valid')),
    sa.CheckConstraint('horizon_years BETWEEN 0 AND 100', name=op.f('ck_risk_profiles_horizon_range')),
    sa.CheckConstraint('risk_score BETWEEN 0 AND 100', name=op.f('ck_risk_profiles_score_range')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_risk_profiles_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'assessed_at', name=op.f('pk_risk_profiles'))
    )
    op.create_table('holdings_snapshot',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.String(length=10), nullable=False),
    sa.Column('instrument_id', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('avg_cost >= 0', name=op.f('ck_holdings_snapshot_avg_cost_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_holdings_snapshot_quantity_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], name=op.f('fk_holdings_snapshot_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], name=op.f('fk_holdings_snapshot_instrument_id_instruments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('snapshot_date', 'account_id', 'instrument_id', name=op.f('pk_holdings_snapshot'))
    )
    op.create_index(op.f('ix_holdings_snapshot_instrument_id'), 'holdings_snapshot', ['instrument_id'], unique=False)
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("severity IN ('REJECTED', 'WARNING')", name=op.f('ck_import_errors_severity_valid')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_errors_batch_id_import_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_errors'))
    )
    op.create_index(op.f('ix_import_errors_batch_id_line_number'), 'import_errors', ['batch_id', 'line_number'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=12), nullable=False),
    sa.Column('account_id', sa.String(length=10), nullable=False),
    sa.Column('instrument_id', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(transaction_type IN ('BUY','SELL') AND quantity > 0 AND price > 0) OR (transaction_type IN ('DIVIDEND','FEE') AND quantity = 0 AND price = 0)", name=op.f('ck_transactions_trade_vs_cash_shape')),
    sa.CheckConstraint("status IN ('SETTLED', 'PENDING', 'REVERSED')", name=op.f('ck_transactions_status_valid')),
    sa.CheckConstraint("transaction_id ~ '^T[0-9]{7,}$'", name=op.f('ck_transactions_id_format')),
    sa.CheckConstraint("transaction_type IN ('BUY', 'SELL', 'DIVIDEND', 'FEE')", name=op.f('ck_transactions_type_valid')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_transactions_amount_non_negative')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], name=op.f('fk_transactions_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_transactions_import_batch_id_import_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], name=op.f('fk_transactions_instrument_id_instruments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('pk_transactions'))
    )
    op.create_index('ix_transactions_account_date', 'transactions', ['account_id', sa.literal_column('trade_date DESC'), sa.literal_column('transaction_id DESC')], unique=False)
    op.create_index(op.f('ix_transactions_instrument_id'), 'transactions', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_transactions_trade_date'), 'transactions', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_trade_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_instrument_id'), table_name='transactions')
    op.drop_index('ix_transactions_account_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_import_errors_batch_id_line_number'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index(op.f('ix_holdings_snapshot_instrument_id'), table_name='holdings_snapshot')
    op.drop_table('holdings_snapshot')
    op.drop_table('risk_profiles')
    op.drop_index(op.f('ix_import_batches_kind'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_goals_customer_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('staging_transactions')
    op.drop_table('instruments')
    op.drop_table('customers')
    # ### end Alembic commands ###
    op.execute(sa.schema.DropSequence(sa.Sequence("goal_id_seq")))
